/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 39b5b066d3d00bdd4e5d97f801dd9ca6)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ADMISSION: DurableObjectNamespace<import("./demo/worker").AdmissionCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./demo/worker");
		durableNamespaces: "AdmissionCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
